
[project]
name = "kulim"
version = "0.1.0-rc.8"
description = "Korean Unified Linguistic Integration Manager"
authors = [
    { name = "jake1104", email = "iamjake1104@gmail.com" }
]
dependencies = [
    "grammar==0.1.0rc8",
    "hangul==0.0.1",
    "numpy>=2.3.5",
    "torch>=2.7,<2.9"
]
