[project]
name = "hangul"
version = "0.1.0"
requires-python = ">=3.11,<4.0"
description = "KULIM Hangul (Supports Old Hangul)"
license = { text = "CC BY-SA 4.0" }
authors = [
    { name = "jake1104", email = "iamjake1104@gmail.com" }
]
dependencies = [
]
